project:
  type: book

book:
  title: "A clinically relevant spatial single-cell landscape of pancreatic cancer"
  author: "Yali Xie, Rujia Zheng, Yongjing Liu, Yingjiqiong Liang, Jinyan Huang"
  date: "March 20, 2025"
  chapters:
    - index.qmd
    - figure1.qmd
    - figure2.qmd
    - figure3.qmd
    - figure4.qmd
    - figure5.qmd
    - figure6.qmd
    - figure7.qmd
    - sup_figure7.qmd
    - sup_figure8.qmd
    - sup_figure9.qmd
    - sup_figure10.qmd
    - sup_figure11.qmd
    - sup_figure12.qmd
    - sup_figure13.qmd
    - sup_figure14.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false
  pdf:
    documentclass: scrreprt

editor: visual

