default:
  project_name: "hyperion"
  dataset: "qzhang"
colors:
  stype3:
    Surgery_without_chemo: "#B61932"
    Surgery_after_chemo: "#FFE475"
    Paracancerous: "#01A0A6"
    Normal: "#5D9D58"
    Punc_pancreas: "#BCBDDC"
    Punc_liver: "#5589C2"
  cell_type_new:
    CD8+ T cell: "#5D9D58"
    CD4+ T cell: "#7E9A51"
    B cell: "#A9D169"
    MDSC: "#BBA082"
    Monocyte: "#BEA278"
    HLA-DR+CD163- mp: "#FFA428"
    HLA-DR-CD163+ mp: "#F4C321"
    HLA-DR+CD163+ mp: "#DB9721"
    HLA-DR-CD163- mp: "#ECD400"
    HLA-DR+CD163- MMT: "#A56F95"
    HLA-DR+CD163+ MMT: "#BAA4CB"
    HLA-DR-CD163- MMT: "#BCBDDC"
    DC: "#DDBE91"
    Col1+ CAF: "#404BA5"
    myoCAF: "#568AC2"
    PSC: "#86BBDA"
    Vim+ cell: "#B9E0EE"
    Endothelial cell: "#E6939F"
    Normal epithelial cell: "#B61932"
    Epithelial tumor cell: "#F98354"
    B7-H4+ cell: "#DBDB8D"
    CCR6+ cell: "#74DA00"
    Ki67+ cell: "#49BADB"
    Unknown: "#D9D9D9"
  meta_color:
    MC-tumor-core: "#DD3662"
    MC-tumor-frontline: "#CC7AA2"
    MC-stroma-CAF: "#68ABB8"
    MC-stroma-macro: "#63B8FF"
    MC-stroma-mCAF: "#778868"
    MC-DC: "#A9DC67"
    MC-normal: "#67DBA5"
    MC-immune-enriched: "#E4C7F1"
    MC-immune-myeloid: "#826DBA"
    MC-macro-c1: "#FAC484"
    MC-macro-c2: "#F7945D"
  meta_merge:
    MC-tumor-frontline: "#BC3C29FF"
    MC-stroma-macro: "#0072B5FF"
    MC-others: "#E18727FF"
  rctd_colors:
    Tcell: "#7E9A51"
    Bcell: "#a9d169"
    islet: "#BBA082"
    tumor: "#B61932"
    endothelial: "#E6939F"
    fibroblast: "#B9E0EE"
    myeloid: "#FFA428"
    mast: "#BCBDDC"
    plasma: "#dbdb8d"
    acinar: "#568AC2"
  scrna_cells:
    CD8T: "#5D9D58"
    CD4T: "#7E9A51"
    B_cell: "#A9D169"
    DC: "#BBA082"
    ductal: "#B61932"
    endothelial: "#E6939F"
    fibroblast: "#B9E0EE"
    macrophage: "#FFA428"
    Macrophage_DN: "#ECD400"
    mast_cell: "#BCBDDC"
    neutrophil: "#F98354"
    plasma_cell: "#DBDB8D"
    acinar_cell: "#568AC2"
  scmac_type:
    DN_mp: "#BC3C29FF"
    TAM_SPP1: "#BBA082"
    Mac_FCN1: "#F98354"
    Mac_MT1G: "#ECD400"
    TAM_C1QC: "#DB9721"
    Mac_CCL18: "#DDBE91"
